### ISSUE TITLE
Make auto-documentation work

### ISSUE THREAD

**Issue by GabrielKP** [GabrielKP/enc#5]
mkdocs and make an initial example
Potentially makes accessible in the web ?

**Comment by KristijanArmeni** [comment]
I tried deploying the documentation website to this repo (I added `/docs` and `mkdocs.yml` in ab7eae9563e6d888dc9e2ec8370b524a74662132). The docs should be rendered at https://gabrielkp.com/enc/ by default, but it leads to 404. 

see that https://gabrielkp.com exists, so perhaps @GabrielKP we should check gh-pages settings in this repo?

### What was done
I ran `mkdocs gh-deploy` locally (see [here](https://www.mkdocs.org/user-guide/deploying-your-docs/); I have mkdocs and deps installed). And get:
```bash
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/kriarm/project/enc/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - about.md
             
[... some warnings here...]

INFO    -  Documentation built in 0.43 seconds
INFO    -  Copying '/Users/kriarm/project/enc/site' to 'gh-pages' branch and pushing to GitHub.
Enumerating objects: 31, done.
Counting objects: 100% (31/31), done.
Delta compression using up to 10 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (16/16), 1.82 KiB | 1.82 MiB/s, done.
Total 16 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (8/8), completed with 8 local objects.
To https://github.com/GabrielKP/enc
   e42d8e7..57055eb  gh-pages -> gh-pages
INFO    -  Your documentation should shortly be available at: https://GabrielKP.github.io/enc/
```

### Local preview

Running `mkdocs serve` locally in the root folder, it runs fine:
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/06584778-9570-48fc-b466-09177b7c8634">

**Comment by GabrielKP** [comment]
With commit https://github.com/GabrielKP/enc/commit/e53e0a2e4c14f1f75e465c9fc05f81bcd8ade8fd automatic deployment of documentation on push is achieved!
